=== mapsforge/mapsforge-mapcreator/resources/mapcreator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://mapsforge.org/mapcreator" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://mapsforge.org/mapcreator">

	<element name="mapcreator-config" type="tns:config"/>
    
    <complexType name="part">
    	<sequence minOccurs="0" maxOccurs="unbounded">
			<element name="part" type="tns:part"/>
    	</sequence>
		<attribute name="name" type="string" use="required"/>
		<attribute name="create-map" type="boolean" default="true"/>
		<attribute name="create-pbf" type="boolean" default="false"/>
		<attribute name="defines-hierarchy" type="boolean" default="true" use="optional"/>
    	<attribute name="type" default="ram">
    		<simpleType>
    			<restriction base="string">
					<enumeration value="ram"/>
					<enumeration value="hd"/>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="map-start-zoom" default="14">
    		<simpleType>
    			<restriction base="int">
					<minInclusive value="1"/>
					<maxInclusive value="21"/>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="map-start-lat">
    		<simpleType>
    			<restriction base="double">
					<minExclusive value="-90"/>
					<maxExclusive value="90"/>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="map-start-lon">
    		<simpleType>
    			<restriction base="double">
					<minExclusive value="-180.0"/>
					<maxExclusive value="180.0"/>
    			</restriction>
    		</simpleType>
    	</attribute>
		<attribute name="preferred-languages" type="string"/>
    </complexType>


    <complexType name="config">
    	<sequence minOccurs="1" maxOccurs="unbounded">
			<element name="part" type="tns:part"/>
    	</sequence>
		<attribute name="default-map-start-zoom" type="int" use="optional" default="14"/>
		<attribute name="default-preferred-language" type="string" default="en"/>
		<attribute name="pbf-staging-path" type="string" use="optional" default="data"/>
		<attribute name="map-staging-path" type="string" use="optional" default="maps"/>
		<attribute name="map-target-path" type="string" use="required"/>
		<attribute name="polygons-path" type="string" use="optional" default="polygons"/>
		<attribute name="logging-path" type="string" use="required"/>
		<attribute name="initial-source-pbf" type="string" use="optional" default="planet.osm.pbf"/>
		<attribute name="osmosis-path" type="string" default="osmosis"/>
		<attribute name="poi-staging-path" type="string" default="poi-staging-path"/>
		<attribute name="poi-target-path" type="string" default="poi-target-path"/>
		<attribute name="default-preferred-languages" type="string" fixed="en"/>
		<attribute name="zoom-interval-conf" type="string" default=""/>
		<attribute name="land-simplification" type="float" default="0"/>
    </complexType>
</schema>

=== mapsforge/mapsforge-mapcreator/xml/multilingual-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapcreator-config xmlns="http://mapsforge.org/mapcreator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:schemaLocation="http://mapsforge.org/mapcreator mapcreator.xsd " default-map-start-zoom="14" map-staging-path="maps-multilingual"
		   pbf-staging-path="data" polygons-path="polygons" map-target-path="/productfiles/mapsforge/maps/multilingual" logging-path="logs/multilingual" initial-source-pbf="planet.osm.pbf"
		   poi-staging-path="pois"
		   poi-target-path="/productfiles/mapsforge/pois" 
		   osmosis-path="/software/other/osmosis-download/bin/osmosis"
		   default-preferred-language="en,de,fr,es">

  <!-- Russia (top level as it straddles Asia and Europe) -->
  <part name="russia" create-pbf="true" create-map="false">
    <part name="central-federal-district" create-pbf="true" create-map="false" defines-hierarchy="false">
      <part name="moskovskaya" map-start-lat="55.75" map-start-lon="37.62"/>
    </part>
  </part>
  <!-- Europe -->
  <part name="europe" create-pbf="true" create-map="false">
    <!-- Germany -->
    <part name="germany" create-pbf="true" type="hd" map-start-lat="52.525582" map-start-lon="13.370061">
      <part name="berlin" map-start-lat="52.525582" map-start-lon="13.370061" />
    </part>
    
    <!-- France (inside Europe regions) -->
    <part name="france" create-pbf="true" map-start-lat="48.8614" map-start-lon="2.3606">
      <part name="centre" map-start-lat="47.903225" map-start-lon="1.908724"/>
    </part>
    
    <!-- Great Britain -->
    <part name="great_britain" create-pbf="true" map-start-lat="51.499266" map-start-lon="-0.124787">
      <part name="england" map-start-lat="51.50728" map-start-lon="-0.12766" defines-hierarchy="false">
	<part name="greater_london" map-start-lat="51.50728" map-start-lon="-0.12766"/>
      </part>
    </part>
    
    <part name="albania" map-start-lat="41.32737" map-start-lon="19.81864"/>
    <part name="belarus" map-start-lat="53.90226" map-start-lon="27.56186"/>
    <part name="belgium" map-start-lat="50.84654" map-start-lon="4.35168"/>
    <part name="bosnia-herzegovina" map-start-lat="43.85845" map-start-lon="18.42956"/>
    <part name="bulgaria" map-start-lat="42.697687" map-start-lon="23.321764"/>
    <part name="croatia" map-start-lat="45.814713" map-start-lon="15.978413"/>
    <part name="cyprus" map-start-lat="35.1637" map-start-lon="33.3635"/>
    <part name="greece" map-start-lat="37.979166" map-start-lon="23.716682"/>
    <part name="hungary" map-start-lat="47.498532" map-start-lon="19.040766"/>
    <part name="iceland" map-start-lat="64.1473" map-start-lon="-21.9399"/>
    <part name="malta" map-start-lat="35.8972" map-start-lon="14.5203"/>
    <part name="switzerland" map-start-lat="46.948395" map-start-lon="7.445351"/>
    <part name="turkey" map-start-lat="41.005358" map-start-lon="28.978415"/>
    <part name="ukraine" map-start-lat="50.4554" map-start-lon="30.532"/>
  </part>
  <!-- North America -->
  <part name="north-america" create-map="false">
    <!-- United States -->
    <part name="us" create-map="false">
      <part name="us-northeast" create-pbf="true" create-map="false" defines-hierarchy="false">
	<part name="new-york" map-start-lat="40.7222" map-start-lon="-73.9791" />
      </part>
    </part>
      <!-- Canada -->
    <part name="canada" create-pbf="true" create-map="false">
      <part name="quebec" map-start-lat="46.825" map-start-lon="-71.143"/>
    </part>
    <part name="mexico" map-start-lat="19.433333" map-start-lon="-99.133333"/>

  </part>
  <!-- South America -->
  <part name="south-america" create-pbf="true" create-map="false">
    <part name="peru" map-start-lat="-12.05" map-start-lon="-77.04"/>
  </part>
  <!-- Africa -->
  <part name="africa" create-pbf="true" map-start-lat="30.05" map-start-lon="31.2414">
    <part name="burkina_faso" map-start-lat="12.333333" map-start-lon="-1.666667"/>
    <part name="morocco" map-start-lat="34.033333" map-start-lon="-6.85"/>
  </part>
  <!-- Asia -->
  <part name="asia" create-pbf="true" create-map="false">
    <part name="azerbaijan" map-start-lat="40.3818" map-start-lon="49.8967"/>
    <part name="china" map-start-lat="39.9073" map-start-lon="116.3848"/>
    <part name="gaza" map-start-lat="31.51" map-start-lon="34.4573"/>
    <part name="gcc_states" map-start-lat="25.2931" map-start-lon="51.5424"/>
    <part name="india" map-start-lat="28.6098" map-start-lon="77.2146"/>
    <part name="indonesia" map-start-lat="-6.1752" map-start-lon="106.8247"/>
    <part name="iran" map-start-lat="35.6874" map-start-lon="51.4206"/>
    <part name="iraq" map-start-lat="33.3126" map-start-lon="44.3632"/>
    <part name="israel_and_palestine" map-start-lat="31.77743" map-start-lon="35.22472"/>
    <part name="japan" type="hd" map-start-lat="35.683" map-start-lon="139.7634"/>
    <part name="kazakhstan" map-start-lat="51.1597" map-start-lon="71.4609"/>
    <part name="kyrgyzstan" map-start-lat="42.909" map-start-lon="74.593"/>
    <part name="malaysia_singapore_brunei" map-start-lat="1.2991" map-start-lon="103.8466"/>
    <part name="mongolia" map-start-lat="47.9171" map-start-lon="106.9166"/>
    <part name="nepal" map-start-lat="27.7" map-start-lon="85.333333"/>
    <part name="pakistan" map-start-lat="33.6929" map-start-lon="73.061"/>
    <part name="philippines" map-start-lat="14.592" map-start-lon="120.981"/>
    <part name="south-korea" map-start-lat="37.566667" map-start-lon="126.966667"/>
    <part name="taiwan" map-start-lat="25.0408" map-start-lon="121.5677"/>
    <part name="thailand" map-start-lat="13.753" map-start-lon="100.5"/>
    <part name="turkmenistan" map-start-lat="37.9483" map-start-lon="58.3786"/>
    <part name="uzbekistan" map-start-lat="41.3134" map-start-lon="69.2833"/>
    <part name="vietnam" map-start-lat="21.02921" map-start-lon="105.85247"/>
  </part>
</mapcreator-config>
